RegisterNetEvent('rebel_firepanel:create_fire_blip', function(coords)
    local blip = AddBlipForCoord(coords.x, coords.y, coords.z)
    SetBlipSprite(blip, 436)
    SetBlipDisplay(blip, 4)
    SetBlipScale(blip, 1.0)
    SetBlipColour(blip, 1)
    SetBlipAsShortRange(blip, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString("Active Fire")
    EndTextCommandSetBlipName(blip)
    Wait(900000)
    RemoveBlip(blip)
end)
